version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: capybara
    versions:
    - 3.35.1
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: unicorn
    versions:
    - 5.8.0
